version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Dushanbe
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      android-build-tooling:
        patterns:
          - "com.android.*"
          - "org.jetbrains.kotlin*"
      androidx:
        patterns:
          - "androidx.*"
      quality-tooling:
        dependency-type: development
        patterns:
          - "io.gitlab.arturbosch.detekt*"
          - "org.jetbrains.kotlinx.kover*"
          - "org.jlleitschuh.gradle.ktlint*"
      runtime-observability:
        patterns:
          - "com.jakewharton.timber*"
          - "io.sentry*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "04:30"
      timezone: Asia/Dushanbe
    open-pull-requests-limit: 10
    commit-message:
      prefix: chore
      include: scope
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: Asia/Dushanbe
    open-pull-requests-limit: 5
    commit-message:
      prefix: chore
      include: scope
    groups:
      verification-images:
        patterns:
          - "*"
